project: au88
shortpath: /scratch/au88
laboratory: access-om3-isomip-nuopc

modules:
    use:
        - /g/data/vk83/modules
    load:
        - access-om3/2026.03.000

queue: normalsr
ncpus: 49
walltime: 1:00:00
jobname: nuopc_isomip_ocn
jobfs: 10GB

model: access-om3
exe: /g/data/au88/jr5971/access3-share-isomip/install-mom6-isomip/bin/access-om3-MOM6
input:
    - ./INPUT

runlog: false
metadata:
    enable: false

platform:
    nodesize: 104
    nodemem: 512

collate: false

userscripts:
    setup: /usr/bin/python3 tools/patch_ocean_only_runconfig.py
    archive: /usr/bin/bash /g/data/vk83/apps/om3-scripts/payu_config/archive.sh

qsub_flags: -W umask=027

restart_freq: 1YS
payu_minimum_version: 1.3.2

storage:
    scratch:
        - au88
    gdata:
        - au88
        - vk83
