#!/usr/bin/env python3
"""Select the active MOM6 geometry override in input.nml."""

from __future__ import annotations

from argparse import ArgumentParser
from dataclasses import dataclass
from pathlib import Path
import re


BASE_PARAMETER_FILES = ("MOM_input", "MOM_override")
ACTIVE_OVERRIDE = "MOM_override.gfz_active"


@dataclass(frozen=True)
class GeometryCase:
    case_name: str
    initial_file: str
    shelf_mass_file: str | None = None
    geometry_file: str | None = None


GEOMETRY_CASES = {
    "ocean3-static": GeometryCase(
        case_name="Ocean3 static",
        initial_file="gfz_geometry/Ocean3_2km_initial.nc",
    ),
    "ocean3-noop": GeometryCase(
        case_name="Ocean3 dynamic no-op",
        initial_file="gfz_geometry/Ocean3_2km_initial.nc",
        shelf_mass_file="gfz_geometry/Ocean3_2km_shelf_mass_noop.nc",
    ),
    "ocean3": GeometryCase(
        case_name="Ocean3 dynamic",
        initial_file="gfz_geometry/Ocean3_2km_initial.nc",
        shelf_mass_file="gfz_geometry/Ocean3_2km_shelf_mass.nc",
    ),
    "ocean3-geometry-noop": GeometryCase(
        case_name="Ocean3 prescribed geometry no-op",
        initial_file="gfz_geometry/Ocean3_2km_initial.nc",
        geometry_file="gfz_geometry/Ocean3_2km_geometry_noop.nc",
    ),
    "ocean3-geometry": GeometryCase(
        case_name="Ocean3 prescribed geometry",
        initial_file="gfz_geometry/Ocean3_2km_initial.nc",
        geometry_file="gfz_geometry/Ocean3_2km_geometry.nc",
    ),
    "ocean4-static": GeometryCase(
        case_name="Ocean4 static",
        initial_file="gfz_geometry/Ocean4_2km_initial.nc",
    ),
    "ocean4-noop": GeometryCase(
        case_name="Ocean4 dynamic no-op",
        initial_file="gfz_geometry/Ocean4_2km_initial.nc",
        shelf_mass_file="gfz_geometry/Ocean4_2km_shelf_mass_noop.nc",
    ),
    "ocean4": GeometryCase(
        case_name="Ocean4 dynamic",
        initial_file="gfz_geometry/Ocean4_2km_initial.nc",
        shelf_mass_file="gfz_geometry/Ocean4_2km_shelf_mass.nc",
    ),
    "ocean4-geometry-noop": GeometryCase(
        case_name="Ocean4 prescribed geometry no-op",
        initial_file="gfz_geometry/Ocean4_2km_initial.nc",
        geometry_file="gfz_geometry/Ocean4_2km_geometry_noop.nc",
    ),
    "ocean4-geometry": GeometryCase(
        case_name="Ocean4 prescribed geometry",
        initial_file="gfz_geometry/Ocean4_2km_initial.nc",
        geometry_file="gfz_geometry/Ocean4_2km_geometry.nc",
    ),
}
CASE_CHOICES = ("baseline",) + tuple(GEOMETRY_CASES)


def format_parameter_files(files: tuple[str, ...]) -> str:
    return ", ".join(f"'{name}'" for name in files)


def replace_parameter_filename(text: str, files: tuple[str, ...]) -> str:
    replacement = f"    parameter_filename = {format_parameter_files(files)} /"
    pattern = r"^\s*parameter_filename\s*=.*?/\s*$"
    updated, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise RuntimeError(f"Expected one parameter_filename setting, found {count}")
    return updated


def replace_override_setting(text: str, key: str, value: str) -> str:
    pattern = rf'^(#override\s+{re.escape(key)}\s*=\s*)".*?"(\s*)$'
    replacement = rf'\g<1>"{value}"\g<2>'
    updated, count = re.subn(pattern, replacement, text, count=1, flags=re.MULTILINE)
    if count != 1:
        raise RuntimeError(f"Expected one {key} setting in MOM_override, found {count}")
    return updated


def geometry_block(geometry: GeometryCase) -> str:
    lines = [
        "",
        f"! Generated by tools/set_gfz_geometry_case.py for {geometry.case_name}.",
        "! This file is a full override file; do not stack it after MOM_override.",
        "#override ICE_THICKNESS_VARNAME = \"thick\"",
        "#override ICE_AREA_VARNAME = \"area\"",
        "#override SURFACE_PRESSURE_VAR = \"thick\"",
        "#override SURFACE_PRESSURE_SCALE = 8820.0",
        "#override DENSITY_ICE = 900.0",
        "#override MIN_THICKNESS_SIMPLE_CALVE = 10.0",
    ]
    if geometry.shelf_mass_file:
        lines.extend(
            [
                "",
                "#override DYNAMIC_SHELF_MASS = True",
                "#override OVERRIDE_SHELF_MOVEMENT = True",
                "#override ICE_SHELF_MASS_FROM_FILE = True",
                "#override ICE_SHELF_CONFIG = \"file\"",
                f"#override SHELF_FILE = \"{geometry.shelf_mass_file}\"",
                "#override SHELF_MASS_VAR = \"shelf_mass\"",
                "",
                "#override CONST_SEA_LEVEL = True",
                "#override CONST_SEA_LEVEL_MISOMIP = True",
            ]
        )
    if geometry.geometry_file:
        lines.extend(
            [
                "",
                "#override DYNAMIC_SHELF_MASS = True",
                "#override OVERRIDE_SHELF_MOVEMENT = True",
                "#override ICE_SHELF_GEOMETRY_FROM_FILE = True",
                f"#override SHELF_GEOMETRY_FILE = \"{geometry.geometry_file}\"",
                "#override SHELF_GEOMETRY_THICKNESS_VAR = \"thick\"",
                "#override SHELF_GEOMETRY_BASE_VAR = \"base_elevation\"",
                "#override SHELF_GEOMETRY_FLOATING_FRACTION_VAR = \"floating_fraction\"",
                "#override SHELF_GEOMETRY_READ_BED = True",
                "#override SHELF_GEOMETRY_BED_VAR = \"bed_elevation\"",
                "#override SHELF_GEOMETRY_READ_GROUNDED = False",
                "#override SHELF_GEOMETRY_GROUNDED_FRACTION_VAR = \"grounded_fraction\"",
                "",
                "#override DYNAMIC_CAVITY_GEOMETRY = False",
                "#override DYNAMIC_CAVITY_ALLOW_DRYING = False",
                "#override DYNAMIC_CAVITY_MIN_DEPTH_M = 1.0",
                "#override ICE_SHELF_USTAR_FROM_VEL_BUGFIX = True",
            ]
        )
    return "\n".join(lines) + "\n"


def write_active_override(base_override: Path, active_override: Path, geometry: GeometryCase) -> None:
    text = base_override.read_text(encoding="utf-8")
    text = replace_override_setting(text, "ICE_THICKNESS_FILE", geometry.initial_file)
    text = replace_override_setting(text, "SURFACE_PRESSURE_FILE", geometry.initial_file)
    text = text.rstrip() + "\n" + geometry_block(geometry)
    active_override.write_text(text, encoding="utf-8")


def main() -> None:
    parser = ArgumentParser()
    parser.add_argument("case", choices=CASE_CHOICES)
    parser.add_argument("--input-nml", type=Path, default=Path("input.nml"))
    parser.add_argument("--base-override", type=Path, default=Path("MOM_override"))
    parser.add_argument("--active-override", type=Path, default=Path(ACTIVE_OVERRIDE))
    args = parser.parse_args()

    if args.case == "baseline":
        files = BASE_PARAMETER_FILES
    else:
        write_active_override(
            base_override=args.base_override,
            active_override=args.active_override,
            geometry=GEOMETRY_CASES[args.case],
        )
        files = ("MOM_input", args.active_override.name)

    text = args.input_nml.read_text(encoding="utf-8")
    text = replace_parameter_filename(text, files)
    args.input_nml.write_text(text, encoding="utf-8")

    print(f"Set {args.input_nml} geometry case to {args.case}")
    print(f"parameter_filename = {format_parameter_files(files)}")
    if args.case != "baseline":
        print(f"Wrote {args.active_override}")


if __name__ == "__main__":
    main()
